In [1]:
#꼭 알아야할 패키지중 하나이다

In [4]:
import numpy as np    #numpy를 불러오고 np라고 줄여서 부르겠다
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
# 0으로 초기화된 배열
arr = np. zeros ((3,3))      #0으로 가득찬 배열
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# 빈 값으로 만들어진 배열
arr = np.empty((4,4))
print(arr)

[[1.30723604e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [10]:
#1로 가득찬 배열을 만든다
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
#배열의 생성
arr = np.arange(10)
print (arr)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
# ndarray 배열의 모양, 차수 데이터 타입 확인
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
arr.shape

(2, 4)

In [18]:
arr.ndim # 차원을 나타냄

2

In [19]:
arr.dtype # 데이터 타입을 나타냄

dtype('int64')

In [20]:
arr_float = arr.astype(np.float64) #실수형 타입으로 바꾸는법
arr_float.dtype

dtype('float64')

In [22]:
arr_str= np.array([f'1','2','3'])
arr_str.dtype

dtype('<U1')

In [23]:
arr_int = arr_str.astype(np.int64) #타입을 다시 정수로 바꾸겠다
arr_int.dtype

dtype('int64')

In [25]:
#ndarray 배열의 연산
arr1 = np.array([[1,2],[3,4]])

arr2 = np.array([[5,6],[7,8]])

In [27]:
arr1+ arr2 #덧셈1


array([[10, 12],
       [14, 16]])

In [28]:
np.add(arr1,arr2)#덧셈2

array([[10, 12],
       [14, 16]])

In [30]:
arr1 * arr2 #곱셈1

array([[25, 36],
       [49, 64]])

In [31]:
np.multiply(arr1, arr2)

array([[25, 36],
       [49, 64]])

In [33]:
# ndarray 배열 슬라이싱 하기
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [35]:
arr .ndim # 차원수

2

In [39]:
arr_1 = arr[:2,1:3]
print(arr_1)

[[2 3]
 [5 6]]


In [40]:
arr[0,2]

3

In [41]:
arr[0,1:-1]

array([2])

In [42]:
arr[[0,1,2],[2,0,1]]

array([3, 4, 8])

In [43]:
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [44]:
print(arr[idx])

[4 5 6 7 8 9]


In [68]:
redwine=np.loadtxt(fname='winequality-red(1).csv', delimiter=';', skiprows=1)
print(redwine)

OSError: ignored

In [58]:
# 합계 
print(redwine.sum())

NameError: ignored

In [50]:
#평균
print(redwine.mean())

NameError: ignored

In [51]:
#축(axis)
print(redwine.sum(axis=0))

NameError: ignored

In [55]:
print(redwine.mean(axis=0))

NameError: ignored

In [61]:
redwine[:,0].mean()

NameError: ignored

In [62]:
redwine.max(axis=0)

NameError: ignored

In [63]:
redwine.min(axis=0)

NameError: ignored